Make program-fpga detect board type

diff --git a/program-fpga b/program-fpga
--- a/program-fpga
+++ b/program-fpga
@@ -2,11 +2,26 @@
 
 PATH="${PATH}:."
 
+if [ -f /sys/class/gpio/gpio69/value ]; then
+# beaglebone
+nCONFIG="/sys/class/gpio/gpio67/value"
+CONFIG_DONE="/sys/class/gpio/gpio66/value"
+nSTATUS="/sys/class/gpio/gpio69/value"
+SPI="/dev/spidev1.0"
+CODE="${1:-spimux.rbf}"
+MUX=1-0070
+elif [ -f /sys/class/gpio/gpio21/value ]; then
+# raspberry pi
 nCONFIG="/sys/class/gpio/gpio13/value"
 CONFIG_DONE="/sys/class/gpio/gpio26/value"
 nSTATUS="/sys/class/gpio/gpio21/value"
 SPI="/dev/spidev0.0"
-CODE="${1:-spimux.rbf}"
+CODE="${1:-spimux-titan.rbf}"
+MUX=0-0070
+else
+echo "ERROR: Unknown controller board"
+exit 1
+fi
 
 ioget() {
 	eval cat \$$1
@@ -28,7 +43,7 @@ iocheck() {
 }
 
 # Remove I2C MUX if present
-echo 1-0070 > /sys/bus/i2c/drivers/pca954x/unbind 2>/dev/null
+echo $MUX > /sys/bus/i2c/drivers/pca954x/unbind 2>/dev/null
 
 # Configure SPI parameters
 spi-test -C -s 5000000 -b 8 -D $SPI -q 00
@@ -52,7 +67,7 @@ iocheck CONFIG_DONE 1 when nCONFIG is HIGH
 
 
 # Enable i2c MUX
-echo 1-0070 > /sys/bus/i2c/drivers_probe
+echo $MUX > /sys/bus/i2c/drivers_probe
 
 # Configure LCD
 lcd-message --init -l 2 $(basename $CODE .rbf | sed -e 's/_bitrev//' -e 's/_pad//' ) 2>/dev/null
